version: "3.8"

volumes:
  forex-mysqldata:

services:
  
  mysqldb:
    restart: always
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
    environment:
      - MYSQL_DATABASE=forex
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - forex-mysqldata:/var/lib/mysql
      - ./mysqldump/schema.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "3306:3306"
